// Validation Interceptor - Single Responsibility: Input validation
import { validateUserInput } from "@repo/security/validation";
import { HTTP_STATUS } from "@repo/utils/common/constants";
import type { RequestInterceptor, HttpRequestContext } from '../types/http-types';
import { ApiError } from '../handlers/response-handler';

export class ValidationRequestInterceptor implements RequestInterceptor {
  
  async intercept(context: HttpRequestContext): Promise<HttpRequestContext> {
    // Skip validation for internal API endpoints (especially reference endpoints)
    // These are server-generated URLs that should be trusted
    if (this.isInternalApiEndpoint(context.url)) {
      return context;
    }

    // Validate endpoint URL for basic security threats
    const urlValidation = this.validateApiEndpoint(context.url);
    if (!urlValidation.valid) {
      // Debug logging to understand what's being flagged
      if (process.env.NODE_ENV === 'development') {
        console.error('🚫 ValidationRequestInterceptor: URL validation failed', {
          url: context.url,
          errors: urlValidation.errors,
          method: context.method
        });
      }
      
      throw new ApiError(
        `Invalid endpoint: ${urlValidation.errors.join(', ')}`,
        "VALIDATION_ERROR",
        HTTP_STATUS.BAD_REQUEST
      );
    }

    return context;
  }

  /**
   * Check if this is an internal API endpoint that should be trusted
   */
  private isInternalApiEndpoint(url: string): boolean {
    // Trust internal API paths that are generated by the system
    const internalApiPatterns = [
      /^\/[^\/]+\/[^\/]+\/ref(\?.*)?$/,           // Module reference endpoints: /app/module/ref
      /^\/api\//,                                // Internal API routes
      /^\/auth\//,                               // Auth endpoints
    ];

    return internalApiPatterns.some(pattern => pattern.test(url));
  }

  /**
   * Validate API endpoint URL for security threats
   * More lenient than general user input validation
   */
  private validateApiEndpoint(url: string): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!url) {
      return { valid: true, errors };
    }

    // Check for script injection attempts - be very specific to avoid false positives
    const dangerousPatterns = [
      /<script[\s>]/gi,                    // <script> tag
      /<\/script>/gi,                      // </script> tag
      /<iframe[\s>]/gi,                    // <iframe> tag  
      /<\/iframe>/gi,                      // </iframe> tag
      /javascript\s*:/gi,                  // javascript: protocol
      /vbscript\s*:/gi,                    // vbscript: protocol
      /on\w+\s*=\s*["'][^"']*["']/gi,     // event handlers like onclick="..."
      /<object[\s>]/gi,                    // <object> tag
      /<embed[\s>]/gi,                     // <embed> tag
      /<link[\s>]/gi,                      // <link> tag
      /<meta[\s>]/gi,                      // <meta> tag
    ];

    for (const pattern of dangerousPatterns) {
      if (pattern.test(url)) {
        errors.push("URL contains potentially malicious script content");
        break;
      }
    }

    // Check for obvious SQL injection attempts (but allow normal query parameters)
    // Only check for clearly malicious patterns, not just SQL keywords
    const maliciousSqlPatterns = [
      /('|\-\-|;|\/\*|\*\/)/,  // SQL metacharacters
      /(union\s+select|drop\s+table|delete\s+from|insert\s+into|update\s+set)/gi, // Common SQL injection patterns
    ];

    for (const pattern of maliciousSqlPatterns) {
      if (pattern.test(url)) {
        errors.push("URL contains potentially malicious SQL patterns");
        break;
      }
    }

    return {
      valid: errors.length === 0,
      errors
    };
  }
}